// <auto-generated />
using System;
using LibraryManagementSystemEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystemEF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240924153343_DbSetForGenres")]
    partial class DbSetForGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            GenreId = 1,
                            Title = "The Great Gatsby",
                            Year = 1925
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            GenreId = 2,
                            Title = "To Kill a Mockingbird",
                            Year = 1960
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            GenreId = 3,
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            GenreId = 4,
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            GenreId = 5,
                            Title = "The Catcher in the Rye",
                            Year = 1951
                        });
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.BorrowedBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookDetailsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 9, 24, 18, 33, 43, 305, DateTimeKind.Local).AddTicks(9612));

                    b.Property<string>("GenreSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("IsReturned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("YearSnapshot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookDetailsId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gazetteers"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.LibraryBook", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("LibraryBooks");
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.Author", b =>
                {
                    b.HasBaseType("LibraryManagementSystemEF.Entities.User");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.HasDiscriminator().HasValue("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "AuthorOne@exmaple.com",
                            Name = "Author One",
                            Password = "password",
                            Biography = "Author One Biography"
                        },
                        new
                        {
                            Id = 2,
                            Email = "AuthorTwo@exmaple.com",
                            Name = "Author Two",
                            Password = "password",
                            Biography = "Author Two Biography"
                        },
                        new
                        {
                            Id = 3,
                            Email = "AuthorThree@exmaple.com",
                            Name = "Author Three",
                            Password = "password",
                            Biography = "Author Three Biography"
                        },
                        new
                        {
                            Id = 4,
                            Email = "AuthorFour@exmaple.com",
                            Name = "Author Four",
                            Password = "password",
                            Biography = "Author Four Biography"
                        },
                        new
                        {
                            Id = 5,
                            Email = "AuthorFive@exmaple.com",
                            Name = "Author Five",
                            Password = "password",
                            Biography = "Author Five Biography"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.Librarian", b =>
                {
                    b.HasBaseType("LibraryManagementSystemEF.Entities.User");

                    b.Property<DateTime>("DateOfEmployment")
                        .HasColumnType("datetime2");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Librarian");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Email = "ahmedSmith@exmaple.com",
                            Name = "Ahmed Smith",
                            Password = "ahmed123",
                            DateOfEmployment = new DateTime(2024, 9, 24, 18, 33, 43, 307, DateTimeKind.Local).AddTicks(1440),
                            Salary = 5000
                        });
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.Member", b =>
                {
                    b.HasBaseType("LibraryManagementSystemEF.Entities.User");

                    b.Property<DateTime>("DateOfMembership")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 9, 24, 18, 33, 43, 308, DateTimeKind.Local).AddTicks(3639));

                    b.Property<int>("MembershipDuration")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Member");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Email = "johnDoe@example.com",
                            Name = "John Doe",
                            Password = "john123",
                            DateOfMembership = new DateTime(2024, 9, 24, 18, 33, 43, 308, DateTimeKind.Local).AddTicks(4740),
                            MembershipDuration = 30
                        },
                        new
                        {
                            Id = 7,
                            Email = "janDoe@example.com",
                            Name = "Jane Doe",
                            Password = "jane123",
                            DateOfMembership = new DateTime(2024, 9, 24, 18, 33, 43, 308, DateTimeKind.Local).AddTicks(4753),
                            MembershipDuration = 30
                        });
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagementSystemEF.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystemEF.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.BorrowedBook", b =>
                {
                    b.HasOne("LibraryManagementSystemEF.Entities.Book", "BookDetails")
                        .WithMany()
                        .HasForeignKey("BookDetailsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LibraryManagementSystemEF.Entities.Member", "Member")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookDetails");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.LibraryBook", b =>
                {
                    b.HasOne("LibraryManagementSystemEF.Entities.Book", "Book")
                        .WithOne()
                        .HasForeignKey("LibraryManagementSystemEF.Entities.LibraryBook", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementSystemEF.Entities.Member", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
